### PR TITLE
Fix skin for 1.35

### LINKED ISSUE #24: Upgrading to Mediawiki 1.35 seems to have broken something
Something seems to have gone a bit awry with this skin after the wiki was upgraded from 1.34 to 1.35:

image

### PR DESCRIPTION
**Pull request by jdlrobson**
This begins work on fixing the skin for 1.35. 
What happened is that Vector code was completely rewritten in 1.35. To rectify this I had to  use Vector's 1.34 branch as a reference to restore the code needed for this skin to work.

While there, since I'm using 1.37 I had to make various other changes to address other issues that are going to break in future.

The issues with broken / deprecated code are addressed in this patchset (feel free to merge the work so far), but I still need to fix some of the styles (particularly the footer). For that I need to see some screenshots of how this is supposed to behave.
I'll work on that later.
 
cc @tomhughes 

Fixes: #24

### CODE REVIEW

**Comment by tomhughes** [comment]
Thanks for that - it has now been deployed.

There was one remaining issue with https://github.com/osmfoundation/osmf-mediawiki-skin/blob/master/OSMFoundationTemplate.php#L257 that caused an exception to be thrown. I've temporarily patched that in the deployed version for now.

There's a new "Retrieved from" line just above the footer, and some new links in the footer (but that might be deliberate).

**Comment by tomhughes** [comment]
Ah those links used to be in the "More" menu but no longer are.

**Comment by tordanik** [comment]
Not hiding the "edit", "history", ... links behind "more" seems like an improvement. Several people had trouble finding them before.

These are the remaining issues I'm seeing:

* the former version of the logo is used
* there's now a large, non-functional "Variants" link in the footer
* the "Retrieved from" line and the empty box below it probably shouldn't be there.

**Comment by jdlrobson** [comment]
The logo is now controlled by config. You'll need to point to it like so (using whatever the correct path is to your skin folder):

```
$wgLogo['1x'] = "https://wiki.osmfoundation.org/w/skins/OSMFoundation/img/logo.png";
```

**Comment by jdlrobson** [comment]
>> there's now a large, non-functional "Variants" link in the footer
>> the "Retrieved from" line and the empty box below it probably shouldn't be there.

I think this is because you are not using 1.36 which provides these styles. Easily patched. We'll just need to remember to move in future. 

You can add the following rule to MediaWiki:Common.css until you upgrade to fix that:

```
.emptyPortlet, .printfooter { display: none; }

```

**Comment by tomhughes** [comment]
Fixed the logo in https://github.com/openstreetmap/chef/commit/a42fbed9ef1a19a8f92adb6f0b22f68691bf23af.

I'll have a look at upgrading over the weekend.

Any thoughts on the best permanent fix for that exception causing line I pointed out?

**Comment by jdlrobson** [comment]
I sent a pull request: https://github.com/osmfoundation/osmf-mediawiki-skin/pull/27

**Comment by tomhughes** [comment]
Ah sorry I missed that as I wasn't watching this repository... I've merged it now.

**Comment by tomhughes** [comment]
So I update to 1.37 but that seems to have broken things again, with basically no styling being applied :-(

**Comment by tomhughes** [comment]
Found this in the delivered CSS code:

```
/*
[f2a0fb564600377c18437ecf] 2022-01-01 12:50:33: Fatal exception of type "Less_Exception_Parser"

Problematic modules: {"skins.osmfoundation":"error"}
*/
```

**Comment by tomhughes** [comment]
Looks like https://github.com/osmfoundation/osmf-mediawiki-skin/commit/0af2ae03c1100b914b1c7eabe218ae36bcc224eb has fixed it.

**Pull request merged**
